### ISSUE TITLE
[Issue] Combinational Generation with Dynamic Prompts

### ISSUE THREAD

**Issue by NDWaffles** [acorderob/sd-webui-prompt-postprocessor#10]
## Current Behavior

When PPP is active, Combinational Generations in the Dynamic prompts tab does not function, and will only generate a single image.
Does not seem to put an error in console.

## Expected Behavior

When Combinational Generations is checked, every combination of prompts from both wildcards and dynamic prompts({prompta|promptb}) is found and is used to generate images.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Enable PPP
2. Create prompt with wildcards or dynamic prompts with multiple choices.
3. Attempt to use Combinational Generations under Dynamic prompt tabs.

- Webui Forge version: [f0.0.17v1.8.0rc-latest-278-gbfee03d8]

**Comment by acorderob** [comment]
The only thing that could be happening is that if PPP it is loaded before Dynamic Prompts and the "Process wildcards" option is enabled, it will process the wildcards/choices before Dynamic Prompts gets the prompt, so when it gets the prompt there are no more choices to do the combinatorial.

Try disabling that setting, and if it works you can try to load the extensions in the correct order you need. They load in alphabetical order, just rename one of the folders.

Note that PPP can now replace DP except for some specific things like the combinatorial mode.

**Comment by NDWaffles** [comment]
Update fixed the issues I was having. Thanks for your help, and thanks for making this useful extension!
