### ISSUE TITLE
[Request] ComfyUI node without model input

### ISSUE THREAD

**Issue by qrrbszopgu** [acorderob/sd-webui-prompt-postprocessor#12]
It would be nice if there was a second node that didn't need a model input, maybe with just the model name as a text? 

For using it in workflows where I just need processing for positive/negative prompt text but not generating locally. I know I can attach a dummy model but would rather not keep loading it for every run.

**Comment by acorderob** [comment]
I will think about it. Maybe setting the model as optional. But it is needed for the model variables, so it would reduce functionality.

**Comment by qrrbszopgu** [comment]
thank you, when I generate using an API it would be nice to save the RAM

**Comment by acorderob** [comment]
Just released a new version. Let me know if this works for you. You can let the model be disconnected or connect a string with the models class name so the system variables keep working. You can check the env_info variable in ppp_comfyui.py to see which values to use.

**Comment by acorderob** [comment]
Note that you will have to create again the node or weird things happen with the inputs.
