### ISSUE TITLE
[Issue] Want to give this addon a try but got a error "object of type 'NoneType' has no len()"

### ISSUE THREAD

**Issue by Ptibouc77** [acorderob/sd-webui-prompt-postprocessor#6]
When i try to use this extension i get this error:

`*** Error running process: C:\amd_sd\stable-diffusion-webui-directml\extensions\sd-webui-sendtonegative\scripts\extension.py
    Traceback (most recent call last):
      File "C:\amd_sd\stable-diffusion-webui-directml\modules\scripts.py", line 619, in process
        script.process(p, *script_args)
      File "C:\amd_sd\stable-diffusion-webui-directml\extensions\sd-webui-sendtonegative\scripts\extension.py", line 41, in process
        for i in range(len(p.all_hr_prompts)):  # pylint: disable=consider-using-enumerate
    TypeError: object of type 'NoneType' has no len()`

I use the DML version of Automatic1111 (latest version): https://github.com/lshqqytiger/stable-diffusion-webui-directml
I have dynamic prompt updated to the latest version.

My dynamic prompt folder load first.

**Comment by acorderob** [comment]
I will fix this, but I'm planning on changing the extension scope and name and i will probably do the fix in the new version. I'll see this weekend.

**Comment by Ptibouc77** [comment]
Thank you for the quick answer, for information i just saw that the extension is working as attended so not really a big issue, i can ignore these errors for now :p
