### ISSUE TITLE
Commas disappears out of the prompt line ends

### ISSUE THREAD

**Issue by Ariloum** [acorderob/sd-webui-prompt-postprocessor#8]
So if my prompt contains new lines (\n\r) this addon removes commas at the end of each line, here is some example on the screenshots:

this one with addon turned off
![2024-02-16 02_35_10-Stable Diffusion](https://github.com/acorderob/sd-webui-prompt-postprocessor/assets/6816952/62277840-88e7-429a-802f-61af79be0bd5)

this one with addon on
![2024-02-16 02_35_37-Stable Diffusion](https://github.com/acorderob/sd-webui-prompt-postprocessor/assets/6816952/81395775-05f4-46c1-b8fa-7265436f26d1)

**Comment by acorderob** [comment]
This is on purpose. Separators (commas) at the start or end of lines are removed. It's part of the cleanup process. Do you have a reason/use case for not doing it?

**Comment by Ariloum** [comment]
> This is on purpose. Separators (commas) at the start or end of lines are removed. It's part of the cleanup process. Do you have a reason/use case for not doing it?

yes, result images with commas and w/o are different. 
I have to manually reapply commas for the images I reuse prompts (from the images generated before I have installed that addon). 
also if I'd like to copy that prompt line in front of another line I have to put comma too in the middle...

is there any reason you are clearing typical commas separator in the end of lines?

**Comment by acorderob** [comment]
I'm removing the commas there because they are unnecessary for reading purposes, and that's the cleaning phase purpose.

If your intention is replicating an old prompt, then just disable the cleaning in the settings (or all the options so nothing gets modified).

I might add an option to disable just this case in the next version.

**Comment by Ariloum** [comment]
I see, adding such an option would be awesome, will be waiting for the update

**Comment by acorderob** [comment]
Use v2.4..0 and deselect the "Remove additional extra separators" option.
