### ISSUE TITLE
[Issue] Latest SDNext Dev release

### ISSUE THREAD

**Issue by DivanoDova** [acorderob/sd-webui-prompt-postprocessor#9]
With the latest SDNext dev release i get this error when trying to use this extension `Skipping unknown extra network: ppp` both old and new command are not working the prompt stay in possitive.

Only `<ppp:stn>prompt<ppp:/stn>` returns me this `error: Skipping unknown extra network: ppp` but nothing using the old way.

**Comment by acorderob** [comment]
It seems to be ignoring any "<...>" tag that is not a real extra network. I have to investigate more, but if these changes end up in master it might not be possible to use these start/stop characters anymore in SDNext.

**Comment by acorderob** [comment]
The cause is a bug introduced some days ago in SDNext dev. I have notified vlad with a comment in the offending commit: https://github.com/vladmandic/automatic/commit/945da97d32bdd9348ab5e9e67f9c5a7b6785a945#r143476011

**Comment by DivanoDova** [comment]
I also suggested on Discord there was a issue with one of the latest commits (last one without this issue is #3f1c236) but didn't found what. Tried a bunch troubleshooting and nothing works (like disabling builtin wildcard support...)

Also the issue is now also on Master Branch.

**Comment by acorderob** [comment]
Good news. Vlad fixed it already in the dev branch.

**Comment by DivanoDova** [comment]
Thank you :)
